<?php

namespace App\Http\Controllers;

use App\CRUDModel;
use App\Customer;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;

class CustomerController extends CRUDController
{
    //
    public function init(){

        $this->model = "Customer";
        $this->action = "customer";
        $this->redirect = "customer"; // /bill/items/1/

        //$this->keys = ['id', 'product_name','potency','packing','hsn_code','mfg_code','gst', 'available'];
        //$this->headers = ['ID', 'Product Name','Potency','Packing','Hsn Code','Mfg Code','Gst', 'Available'];
    }

    public function autocomplete(){
        $term = Input::get('term');

        $results = array();

        /*$queries = DB::table('users')
            ->where('first_name', 'LIKE', '%'.$term.'%')
            ->orWhere('last_name', 'LIKE', '%'.$term.'%')
            ->take(5)->get();*/
        $items = Customer::where('name', 'LIKE', '%'.$term.'%')
            ->whereOr('id', '=', $term)
            ->take(10)
            ->get()
            ->toArray();

        foreach ($items as &$item)
        {
            $item['value'] = $item['id']." ".$item['name'];

        }
        return $items;
    }

    public function store_after($request, $data, $view)
    {
        if(request()->ajax()){
            return ["status" => "success", "customer_id" => $data->id, "customer" => $data];
        } else {
            return parent::store_after($request, $data, $view); // TODO: Change the autogenerated stub
        }

    }
}
